english_easy = ["branch", "oval", "orange", "triangle", "ears", "zebra", "face", "shirt", "cup", "bark", "wheel", "ghost", "snowflake", "daisy", "fork", "nose", "bowl", "bee", "jail", "carrot", "tree", "box", "sun", "lips", "airplane", "eye", "jellyfish", "chicken", "bumblebee", "football", "suitcase", "beach", "angel", "bench", "rock", "zigzag", "nail", "spoon", "ear", "caterpillar", "dragon", "rabbit", "snowman", "starfish", "frog", "mouth", "knee", "flag", "mountain", "desk"]

english_medium = ["trumpet", "open", "minivan", "rake", "drawer", "sponge", "hopscotch", "church", "party", "firefighter", "wagon", "coin", "tub", "sign", "start", "reindeer", "sunburn", "paperclip", "bomb", "treasure", "pinecone", "lipstick", "fang", "spare", "stapler", "safe", "skirt", "cardboard", "toe", "rattle", "baby", "popcorn", "cheetah", "quilt", "page", "monkey", "stocking", "nest", "equator", "bushes", "crater", "truck", "kettle", "cave", "wheelchair", "skate", "bell", "beaver", "garbage", "popsicle"]

english_hard = ["softball", "avocado", "school", "foam", "exercise", "garden hose", "devious", "wobble", "atlas", "costume", "roller coaster", "grandpa", "season", "coastline", "carnival", "last", "ounce", "time machine", "trail", "clown", "baggage", "gasoline", "lung", "weather", "safe", "goblin", "lunch tray", "traffic jam", "ski lift", "fiddle", "yodel", "pilot", "neighborhood", "tank", "tablespoon", "sneeze", "husband", "fizz", "full", "imagine", "gold medal", "electrical outlet", "hospital", "photosynthesis", "startup", "sticky note", "print", "son-in-law", "pickup truck", "cattle"]

polski_easy = ["absolwent", "akumulator", "architekt", "astronauta", "baloniarz", "biblioteka", "biżuteria", "bocianisko", "brokatowy", "chorągiew", "ciekawostka", "cukiernia", "dekoracja", "długopis", "dżunglowy", "egzotyka", "ekranizacja", "elektryka", "fajerwerki", "falowanie", "farmaceuta", "filarmonia", "flamingowy", "fotografik", "futbolowy", "gitarzysta", "gorzelnia", "grafomaniak", "grzeczność", "harmonijka", "helikopter", "hipopotam", "historiografia", "hodowla", "ilustracja", "informatyk", "intelekt", "jabłoniowy", "jagodowy", "kakadu", "kalendarz", "kaligrafia", "kampania", "kapsułka", "karawana", "kardiolog", "katalog", "kierowca", "kinematografia", "klasyczność", "klimatyzacja", "klonowanie", "kolekcjoner", "komedia", "komputer", "konduktor", "konsultant", "kontroler", "kooperacja", "korepetytor", "kostiumowy", "kredytowy", "krystaliczny", "książęcy", "kulturowy", "kwadratowy", "lalkarz", "lamparty", "lekarstwo", "leksykon", "literatura", "lodowisko", "lotnisko", "magazynier", "makaronowy", "malinowy", "management", "manewrowy", "manifestacja", "maratończyk", "marketingowy", "maszynista", "matematyk", "mechanik", "medycyna", "melanżowy", "mikroskop", "milioner", "mineralogia", "mistrzowski", "motocyklista", "muzykalny", "naftowy", "narracja", "naukowiec", "nawigator", "nektarowy", "nostalgia", "obserwator", "odkrywca"]

polski_medium = ["transcendencja", "szczebrzeszyn", "wyimaginowany", "imponderabilia", "lekkoatletyka", "metamorfoza", "prima aprilis", "antyterrorysta", "konstantynopolitański", "malkontent", "emulgacja", "emulacja", "onomatopeja", "oksymoron", "tranzystor", "florystyka", "ekstrapolacja", "frywolne zakonnice", "antyterrorystyczne karaluchy", "aleksandryjskie królestwo", "wyimaginowany konsultant", "europarlamentarzysta ortodoksyjny", "gawiedź onieśmielona", "podatek katastralny", "ewidencja podatkowa"]

polski_hard = ["gżegżółka", "żółć", "wizaż", "chrząszcz", "pszenżyto", "krztusiec", "rzeżucha", "rzeżączka", "skrzyżować", "spółgłoska", "dźwiękonaśladownictwo", "dwudziestogroszówka", "Niepodległościowiec", "lumpenproletariat", "wyselekcjonowany", "przeintelektualizować", "średniozmineralizowana", "niepodległościowiec", "niezdyscyplinowanie", "międzykontynentalny", "polisacharyd", "promieniotwórczość", "franczyzobiorca", "ambiwalentny", "interlokutor"]

